### ISSUE TITLE
One-to-Many Joins with Immutable Case Classes

### ISSUE THREAD

**Issue by neilchaudhuri** [mybatis/scala#36]
I have been wrestling with the most basic join possible--between Person and Address--for hours today, and I would simply like to know if this is possible with immutable case classes. Or do I have to make my fields mutable as in the sample? I would rather I just ask before I go through the extensive effort to make them mutable only to find my code ripped off from the samples still doesn't work.

Thanks.

**Comment by mnesarco** [comment]
Hi Neil,

This project is just a wrapper around mybatis(java), and mybatis was not
designed with immutable classes in mind. So it depends and in any case
using immutable classes with this library is very limited.

I suggest you to use Slick. When I started this project Slick did not exist
yet, but now it is by far a better option.

On Thu, Jun 9, 2016 at 7:38 PM, Neil Chaudhuri <notifications@github.com>
wrote:

> I have been wrestling with the most basic join possible--between Person
> and Address--for hours today, and I would simply like to know if this is
> possible with immutable case classes. Or do I have to make my fields
> mutable as in the sample?
>
> Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mybatis/scala/issues/36>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABCXVUn_P-l0DWA27ciW6BgUsdJDg85Rks5qKLIDgaJpZM4IyiE8>
> .
>



-- 
Frank D. Martínez M.

**Comment by neilchaudhuri** [comment]
Thanks for the reply, Frank. Unfortunately while Slick was my preferred choice initially, it isn't an option because of decisions made above my pay grade.

So I should just go with conventional Scala classes with mutable values then?

**Comment by mnesarco** [comment]
Well , there is a simple example code with immutable case class:

https://github.com/mybatis/scala/blob/master/mybatis-scala-samples/src/main/scala/org/mybatis/scala/samples/select/SelectImmutableSample.scala

But if you need to associate a collection (one-to-many) I am afraid you
have no option but to use a mutable collection.

Cheers,

Frank.

On Fri, Jun 10, 2016 at 8:58 AM, Neil Chaudhuri <notifications@github.com>
wrote:

> Thanks for the reply, Frank. Unfortunately while Slick was my preferred
> choice initially, it isn't an option because of decisions made above my pay
> grade.
>
> So I should just go with conventional Scala classes with mutable values
> then?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/mybatis/scala/issues/36#issuecomment-225189166>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABCXVen8D1bzKTWOa8VKGeStKADab0efks5qKW2TgaJpZM4IyiE8>
> .
>



-- 
Frank D. Martínez M.

**Comment by h3adache** [comment]
I'm not reopening this but you can use mybatis directly with scala with a few tweaks.
I use a custom objectfactory and objectfactorywrapper and all case classes (including one-many relationship case classes).
The object factory that @mnesarco wrote here in this project can help get you started or I can share mine which also handles things like using List
