### ISSUE TITLE
1:M Insert Failing

### ISSUE THREAD

**Issue by neilchaudhuri** [mybatis/scala#37]
I currently have a Person to Address mapping in a 1:M relationship. When I insert a Person bean that has a populated mutable.Seq[Address] in it, I find no exceptions, but the Person instance is inserted while the Address instances are not. I have this in my Person ResultMapping:

```
collection[Address](
      property = "addresses", //as the bean has person.addresses
      resultMap = Address.addressResultMap,
      column = "p_id",
      notNullColumn = "p_id"
    )
```

The  result is the same whether those last two values are there or not--or one at a time.

Is there something I need to add to Address to tell MyBatis (Scala) where Person's foreign key in  Address is? Or what else should I look at to insert the children in this 1:M relationship?

Thanks.

**Comment by mnesarco** [comment]
Hi Neil,

This is not related to mybatis-scala. MyBatis is not an ORM it is something
different. MyBatis is an SQL mapper and it will not insert records for you
as JPA does.

Please read the mybatis documentation here:
http://www.mybatis.org/mybatis-3/ to undestand the general principles and
philosophy of mybatis.

Associated collections and ResultMaps are there for data retrieval, not for
insert/update.

Cheers,

Frank.


On Tue, Jun 14, 2016 at 12:32 PM, Neil Chaudhuri <notifications@github.com>
wrote:

> I currently have a Person to Address mapping in a 1:M relationship. When I
> insert a Person bean that has a populated mutable.Seq[Address] in it, I
> find no exceptions, but the Person instance is inserted while the Address
> instances are not. I have this in my Person ResultMapping:
>
> collectionAddress <http://property%20=>
>
> The result is the same whether those last two values are there or not--or
> one at a time.
>
> Is there something I need to add to Address to tell MyBatis (Scala) where
> Person's foreign key in Address is? Or what else should I look at to insert
> the children in this 1:M relationship?
>
> Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mybatis/scala/issues/37>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABCXVbry18UEFYWexezjVON2VBCC5xNFks5qLuXGgaJpZM4I1kaN>
> .
>



-- 
Frank D. Martínez M.

**Comment by neilchaudhuri** [comment]
I have become fairly familiar  with MyBatis over the last few days, and I am really confused by your comment for several reasons:

- The ability to mutate data doesn't necessarily demand an ORM. Slick is an example.

- The "classic" MyBatis  documentation has [an entire section](http://www.mybatis.org/mybatis-3/sqlmap-xml.html#insert_update_and_delete) dedicated to data mutation.

- Even the MyBatis Scala [samples](https://github.com/mybatis/scala/tree/master/mybatis-scala-samples/src/main/scala/org/mybatis/scala/samples) have code dedicated to data mutation. They just don't do it the way I need it. The 1:M insert example uses Map instead of POJOs.

So I find your comment quite puzzling since there seems to be a lot of contradictory information--including in the samples for this very project.

**Comment by mnesarco** [comment]
1. MyBatis allows data mutation. I didn't say anything different.
2. Mybatis and mybatis-scala allow you to select, insert, update and delete data of course, but it will not do it magically. If you have a 1:M relation you have to insert every record calling the corresponding mapped statement.
3. ResultMaps, Associations, Collections, are "Result" Maps, so, they are there to retrieve data. To insert or update data you don't use ResultMaps.

I detect a general confusion about what mybatis is and how it works, I suggest you to read the documentation and the examples, but mainly try to get the general concepts around mybatis.

There is also a mailing list, where you can ask questions. Creating an issue in github is for reporting Bugs and to propose Enhancements.
