### ISSUE TITLE
[Multi Datasources Support]does it support multi datasources?

### ISSUE THREAD

**Issue by Paleozoic** [mybatis/scala#39]
Any example code for it?
i found mybatis-3-config.dtd :
```xml
<!ELEMENT environments (environment+)>
<!ATTLIST environments
default CDATA #REQUIRED
>
```
but how to change the datasource in the code?

**Comment by mnesarco** [comment]
Hi Paleozoic,

You can create as many Configuration objects as you want and use the appropriate as required.

Look at this: https://github.com/mybatis/scala/blob/master/mybatis-scala-samples/src/main/scala/org/mybatis/scala/samples/select/SelectSample.scala#L52
