### ISSUE TITLE
mybatis-scala-samples  compile error

### ISSUE THREAD

**Issue by epiphyllum** [mybatis/scala#49]
[info] Compiling 15 Scala sources to /Users/hary/workspace/scala/mybatis-scala-samples/target/scala-2.11/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.6. Compiling...
[info]   Compilation completed in 7.338 s
[error] /Users/hary/workspace/scala/mybatis-scala-samples/src/main/scala/org/mybatis/scala/samples/performance/ProfileTest.scala:97: method handle: (callback: org.mybatis.scala.session.ResultContext => Unit)(implicit s: org.mybatis.scala.session.Session)Unit does not take type parameters.
[error]     select.handle[TestBean] { context =>
[error]                  ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 9 s, completed 2017-6-19 20:33:49

**Comment by mnesarco** [comment]
Hi @epiphyllum ,
Please use the sbt build. I am not maintaining the maven build for this project. @hazendaz has been updating the poms but I have never tested it.

**Comment by mnesarco** [comment]
@epiphyllum @hazendaz 
I am very confused now. Many compiler errors even in sbt. But I have changed nothing in years. So I don't know what is happening right now. I will try to do some tests....

**Comment by mnesarco** [comment]
@epiphyllum @hazendaz
Ok. It was my mistake. sbt build was outdated.
fixed in: 4c475d846a577f2f65c2af62ba949ae9d9b17efc
