### ISSUE TITLE
how can I get the generated key of an insert with scala bind?

### ISSUE THREAD

**Issue by yishenggudou** [mybatis/scala#58]
how can I get the generated key of an insert with scala bind?

**Comment by mnesarco** [comment]
You should use key generator a in this example:

https://github.com/mybatis/scala/blob/master/mybatis-
scala-samples/src/main/scala/org/mybatis/scala/samples/
insert/InsertSample.scala

Please send questions to the maillist, issues are for bugs/enhancements.
